/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LeadRouteImport } from './routes/lead'
import { Route as RegionRouteImport } from './routes/region'
import { Route as SchoolRouteImport } from './routes/school'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadRoute = LeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/lead': typeof LeadRoute
  '/region': typeof RegionRoute
  '/school': typeof SchoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/lead': typeof LeadRoute
  '/region': typeof RegionRoute
  '/school': typeof SchoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/lead': typeof LeadRoute
  '/region': typeof RegionRoute
  '/school': typeof SchoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses' | '/lead' | '/region' | '/school'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses' | '/lead' | '/region' | '/school'
  id: '__root__' | '/' | '/courses' | '/lead' | '/region' | '/school'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  LeadRoute: typeof LeadRoute
  RegionRoute: typeof RegionRoute
  SchoolRoute: typeof SchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead': {
      id: '/lead'
      path: '/lead'
      fullPath: '/lead'
      preLoaderRoute: typeof LeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region': {
      id: '/region'
      path: '/region'
      fullPath: '/region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  LeadRoute: LeadRoute,
  RegionRoute: RegionRoute,
  SchoolRoute: SchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
